/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppShell {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface TodoCompleted {
        "completed": number;
        "total": number;
    }
    interface TodoItem {
        "name": string;
    }
    interface TodoNotification {
        "duration": number;
    }
}
declare global {
    interface HTMLAppShellElement extends Components.AppShell, HTMLStencilElement {
    }
    var HTMLAppShellElement: {
        prototype: HTMLAppShellElement;
        new (): HTMLAppShellElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLTodoCompletedElement extends Components.TodoCompleted, HTMLStencilElement {
    }
    var HTMLTodoCompletedElement: {
        prototype: HTMLTodoCompletedElement;
        new (): HTMLTodoCompletedElement;
    };
    interface HTMLTodoItemElement extends Components.TodoItem, HTMLStencilElement {
    }
    var HTMLTodoItemElement: {
        prototype: HTMLTodoItemElement;
        new (): HTMLTodoItemElement;
    };
    interface HTMLTodoNotificationElement extends Components.TodoNotification, HTMLStencilElement {
    }
    var HTMLTodoNotificationElement: {
        prototype: HTMLTodoNotificationElement;
        new (): HTMLTodoNotificationElement;
    };
    interface HTMLElementTagNameMap {
        "app-shell": HTMLAppShellElement;
        "my-component": HTMLMyComponentElement;
        "todo-completed": HTMLTodoCompletedElement;
        "todo-item": HTMLTodoItemElement;
        "todo-notification": HTMLTodoNotificationElement;
    }
}
declare namespace LocalJSX {
    interface AppShell {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface TodoCompleted {
        "completed"?: number;
        "total"?: number;
    }
    interface TodoItem {
        "name"?: string;
        "onTodoItemToggled"?: (event: CustomEvent<any>) => void;
    }
    interface TodoNotification {
        "duration"?: number;
    }
    interface IntrinsicElements {
        "app-shell": AppShell;
        "my-component": MyComponent;
        "todo-completed": TodoCompleted;
        "todo-item": TodoItem;
        "todo-notification": TodoNotification;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-shell": LocalJSX.AppShell & JSXBase.HTMLAttributes<HTMLAppShellElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "todo-completed": LocalJSX.TodoCompleted & JSXBase.HTMLAttributes<HTMLTodoCompletedElement>;
            "todo-item": LocalJSX.TodoItem & JSXBase.HTMLAttributes<HTMLTodoItemElement>;
            "todo-notification": LocalJSX.TodoNotification & JSXBase.HTMLAttributes<HTMLTodoNotificationElement>;
        }
    }
}
